# Generated by Django 5.2.2 on 2025-06-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(default=2500),
        ),
    ]
