# Generated by Django 5.2.2 on 2025-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('PL', 'Post Like'), ('PD', 'Post Dislike'), ('CL', 'Comment Like'), ('CD', 'Comment Dislike'), ('F', 'Follow'), ('M', 'Mention')], max_length=2),
        ),
    ]
